import { Card } from "./types";

export const CARD_CATALOG: Card[] = [
  // Champion Heroes Reward
  {
    id: "tom_brady_reward",
    name: "Tom Brady (Super Bowl MVP)",
    sport: "Football",
    theme: "Reward",
    ovr: 99,
    baseViews: 150000,
    cpm: 35.0,
    quirks: ["#GOAT", "#7Rings"],
    imageUrl: "/players/tom-brady.png",
  },
  // Champion Heroes Collection
  {
    id: "lebron_james_champion",
    name: "LeBron James '16/'20",
    sport: "Basketball",
    theme: "Champion Heroes",
    ovr: 94,
    baseViews: 50000,
    cpm: 20.0,
    quirks: ["#FinalsMVP", "#TheBlock"],
    imageUrl: "/players/lebron-james.png",
  },
  {
    id: "connor_mcdavid_champion",
    name: "Connor McDavid '24",
    sport: "NHL",
    theme: "Champion Heroes",
    ovr: 93,
    baseViews: 42000,
    cpm: 18.0,
    quirks: ["#ConnSmythe", "#PureSpeed"],
  },
  {
    id: "patrick_mahomes_champion",
    name: "Patrick Mahomes '20/'23/'24",
    sport: "Football",
    theme: "Champion Heroes",
    ovr: 93,
    baseViews: 44000,
    cpm: 18.5,
    quirks: ["#MagicThrow", "#SuperBowlMVP"],
    imageUrl: "/players/patrick-mahomes.png",
  },
  {
    id: "stephen_curry_champion",
    name: "Stephen Curry '22",
    sport: "Basketball",
    theme: "Champion Heroes",
    ovr: 92,
    baseViews: 41000,
    cpm: 17.0,
    quirks: ["#NightNight", "#FinalsMVP"],
  },
  {
    id: "freddie_freeman_champion",
    name: "Freddie Freeman '24",
    sport: "Baseball",
    theme: "Champion Heroes",
    ovr: 91,
    baseViews: 38000,
    cpm: 16.0,
    quirks: ["#WalkoffSlam", "#WorldSeriesMVP"],
  },
  {
    id: "cale_makar_champion",
    name: "Cale Makar '22",
    sport: "NHL",
    theme: "Champion Heroes",
    ovr: 90,
    baseViews: 35000,
    cpm: 15.0,
    quirks: ["#ConnSmythe", "#BlueLineDangles"],
  },
  {
    id: "lionel_messi_champion",
    name: "Lionel Messi '22",
    sport: "Soccer",
    theme: "Champion Heroes",
    ovr: 94,
    baseViews: 52000,
    cpm: 21.0,
    quirks: ["#WorldCupWinner", "#GoldenBall"],
    imageUrl: "/players/lionel-messi.png",
  },
  {
    id: "alex_pereira_champion",
    name: "Alex Pereira (3x Defense)",
    sport: "Combat",
    theme: "Champion Heroes",
    ovr: 89,
    baseViews: 32000,
    cpm: 14.5,
    quirks: ["#LeftHookKO", "#TitleDefended"],
    imageUrl: "/players/alex-pereira-editorial.jpg",
  },
  {
    id: "sam_bennett_champion",
    name: "Sam Bennett '25",
    sport: "NHL",
    theme: "Champion Heroes",
    ovr: 88,
    baseViews: 28000,
    cpm: 13.0,
    quirks: ["#StanleyCupChamp"],
  },
  {
    id: "cooper_kupp_champion",
    name: "Cooper Kupp '21",
    sport: "Football",
    theme: "Champion Heroes",
    ovr: 87,
    baseViews: 26000,
    cpm: 12.0,
    quirks: ["#TripleCrown", "#SuperBowlMVP"],
  },
  // Live Series 2026
  {
    id: "shohei_ohtani_live",
    name: "Shohei Ohtani",
    sport: "Baseball",
    theme: "Live Series",
    ovr: 99,
    baseViews: 65000,
    cpm: 22.0,
    quirks: ["#50-50Club", "#TwoWayPhenom"],
  },
  {
    id: "mookie_betts_live",
    name: "Mookie Betts",
    sport: "Baseball",
    theme: "Live Series",
    ovr: 93,
    baseViews: 36000,
    cpm: 16.0,
    quirks: ["#LeadoffIgnite"],
  },
  {
    id: "jackson_holliday_live",
    name: "Jackson Holliday",
    sport: "Baseball",
    theme: "Live Series",
    ovr: 79,
    baseViews: 8500,
    cpm: 4.5,
    quirks: ["#ProspectRise"],
    imageUrl: "/players/jackson-holliday.png",
  },
  {
    id: "andy_pages_live",
    name: "Andy Pages",
    sport: "Baseball",
    theme: "Live Series",
    ovr: 78,
    baseViews: 7500,
    cpm: 4.0,
    quirks: ["#OutfieldCannon"],
  },
  {
    id: "nikola_jokic_live",
    name: "Nikola Jokic",
    sport: "Basketball",
    theme: "Live Series",
    ovr: 98,
    baseViews: 58000,
    cpm: 20.0,
    quirks: ["#TripleDoubleMachine"],
  },
  {
    id: "shai_gilgeous_live",
    name: "Shai Gilgeous-Alexander",
    sport: "Basketball",
    theme: "Live Series",
    ovr: 96,
    baseViews: 50000,
    cpm: 18.0,
    quirks: ["#MiddieMaestro"],
  },
  {
    id: "anthony_edwards_live",
    name: "Anthony Edwards",
    sport: "Basketball",
    theme: "Live Series",
    ovr: 92,
    baseViews: 38000,
    cpm: 15.5,
    quirks: ["#Posterizer"],
  },
  {
    id: "lamar_jackson_live",
    name: "Lamar Jackson",
    sport: "Football",
    theme: "Live Series",
    ovr: 97,
    baseViews: 55000,
    cpm: 19.5,
    quirks: ["#DualThreat"],
  },
  {
    id: "justin_jefferson_live",
    name: "Justin Jefferson",
    sport: "Football",
    theme: "Live Series",
    ovr: 95,
    baseViews: 46000,
    cpm: 17.5,
    quirks: ["#GriddySpecial"],
  },
  {
    id: "nathan_mackinnon_live",
    name: "Nathan MacKinnon",
    sport: "NHL",
    theme: "Live Series",
    ovr: 97,
    baseViews: 52000,
    cpm: 18.5,
    quirks: ["#PowerSkate"],
  },
  {
    id: "auston_matthews_live",
    name: "Auston Matthews",
    sport: "NHL",
    theme: "Live Series",
    ovr: 94,
    baseViews: 40000,
    cpm: 16.0,
    quirks: ["#SniperRelease"],
  },
  {
    id: "igor_shesterkin_live",
    name: "Igor Shesterkin",
    sport: "NHL",
    theme: "Live Series",
    ovr: 91,
    baseViews: 30000,
    cpm: 14.0,
    quirks: ["#BrickWall"],
  },
  {
    id: "kylian_mbappe_live",
    name: "Kylian Mbappe",
    sport: "Soccer",
    theme: "Live Series",
    ovr: 97,
    baseViews: 56000,
    cpm: 20.0,
    quirks: ["#TurboPace"],
  },
  {
    id: "erling_haaland_live",
    name: "Erling Haaland",
    sport: "Soccer",
    theme: "Live Series",
    ovr: 96,
    baseViews: 54000,
    cpm: 19.0,
    quirks: ["#GoalRobot"],
  },
  {
    id: "cristiano_ronaldo_live",
    name: "Cristiano Ronaldo",
    sport: "Soccer",
    theme: "Live Series",
    ovr: 86,
    baseViews: 35000,
    cpm: 15.0,
    quirks: ["#SIUUU"],
    imageUrl: "/players/cristiano-ronaldo.jpg",
  },
  {
    id: "carlos_alcaraz_live",
    name: "Carlos Alcaraz",
    sport: "Tennis",
    theme: "Live Series",
    ovr: 96,
    baseViews: 48000,
    cpm: 18.0,
    quirks: ["#DropShotGod"],
  },
  {
    id: "jannik_sinner_live",
    name: "Jannik Sinner",
    sport: "Tennis",
    theme: "Live Series",
    ovr: 96,
    baseViews: 47000,
    cpm: 18.0,
    quirks: ["#LaserForehand"],
  },
  {
    id: "coco_gauff_live",
    name: "Coco Gauff",
    sport: "Tennis",
    theme: "Live Series",
    ovr: 92,
    baseViews: 36000,
    cpm: 15.0,
    quirks: ["#ClutchChampion"],
    imageUrl: "/players/coco-gauff.png",
  },
  {
    id: "islam_makhachev_live",
    name: "Islam Makhachev",
    sport: "Combat",
    theme: "Live Series",
    ovr: 97,
    baseViews: 51000,
    cpm: 19.0,
    quirks: ["#DagestaniHandcuff"],
  },
  {
    id: "ilia_topuria_live",
    name: "Ilia Topuria",
    sport: "Combat",
    theme: "Live Series",
    ovr: 95,
    baseViews: 44000,
    cpm: 17.5,
    quirks: ["#ElMatadorKO"],
  },
  {
    id: "conor_mcgregor_live",
    name: "Conor McGregor",
    sport: "Combat",
    theme: "Live Series",
    ovr: 83,
    baseViews: 38000,
    cpm: 16.0,
    quirks: ["#Notorious"],
    imageUrl: "/players/conor-mcgregor.png",
  },
];
